# Generated by Django 5.2.4 on 2025-09-21 08:44

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('rate', models.IntegerField(blank=True)),
                ('field', models.CharField(choices=[('food', 'food'), ('vegetable', 'vegetable'), ('dairy', 'dairy'), ('meat', 'meat')], max_length=255)),
                ('quality', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='image.jpg', upload_to=app1.models.upload)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('nutrition', models.TextField()),
                ('benefits', models.TextField()),
                ('usage', models.TextField()),
                ('season', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('fun_facts', models.CharField(max_length=150)),
            ],
        ),
    ]
