# Generated by Django 5.2.4 on 2025-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allitems',
            name='field',
            field=models.CharField(choices=[('food', 'food'), ('vegetable', 'vegetable'), ('dairy', 'dairy'), ('meat', 'meat'), ('mens', 'mens'), ('womens', 'womens'), ('kids', 'kids')], max_length=255),
        ),
    ]
