# Generated by Django 5.2.4 on 2025-09-21 16:13

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_allitems_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='scientific_name',
        ),
        migrations.AlterField(
            model_name='allitems',
            name='field',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('vegetable', 'vegetable'), ('dairy', 'dairy'), ('meat', 'meat'), ('mens', 'mens'), ('womens', 'womens'), ('kids', 'kids')], max_length=255),
        ),
        migrations.AlterField(
            model_name='allitems',
            name='image',
            field=models.ImageField(blank=True, default='image.jpg', upload_to=app1.models.upload),
        ),
        migrations.AlterField(
            model_name='description',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='fun_facts',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='description',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='season',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='usage',
            field=models.TextField(blank=True),
        ),
    ]
