# Generated by Django 5.2.4 on 2025-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_description_scientific_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allitems',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
