# Generated by Django 5.2.4 on 2025-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_allitems_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
