# Generated by Django 5.2.4 on 2025-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_description_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
